LEARNING_RATE = 1e-3
EPOCHS = 10000
BATCH_SIZE = 32
HANDS_PER_GAME = 100

SAVE_INTERVAL = 20
POOL_SAVE_INTERVAL = 20
MAX_POOL_SIZE = 100
KEEP_LATEST_POOL = 20

CHECKPOINT_PATH = "latest_checkpoint.pt"
OPPONENT_POOL_DIR = "opponent_pool"

OPPONENT_SAMPLING_MODE = "linear"   # "uniform" or "linear"
DEVICE = "cpu"