weight_manager:
  model_class: "EvenNet"
  models_dir: "res/models"
  max_models: 100
  keep_latest: 20
  sampling_mode: "linear"   # "uniform" or "linear" or "exponential"

learning_loop:
  learning_rate: 1e-3
  epochs: 10000
  games_per_epoch: 32   # batch size for training
  hands_per_game: 100
  save_interval: 100    # save a checkpoint in case of crash
  save_every: 20        # save a model every N epochs
  checkpoint_dir: "res/checkpoint"
